language: rust

rust:
    - 1.0.0-beta
    - nightly

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

script:
    - cargo build
    - cargo test
    - cargo doc
    - rustdoc --test README.md -L target/debug

after_success:
    - curl https://mvdnes.github.io/rust-docs/travis-doc-upload.sh | sh
