language: rust

rust:
    - 1.0.0-beta
    - nightly

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

script:
    - cargo build
    - cargo test
    - cargo doc
    - rustdoc --test README.md -L target/debug

after_success:
    - .travis/travis-doc-upload.sh
